### ISSUE TITLE
Should support bootstrap-template option

### ISSUE THREAD

**Issue by xrl** [chef/knife-openstack#161] opened 2015-05-05 20:27 UTC
I need to provide custom DNS configuration after the node has been provisioned and before chef has been run but the `--bootstrap-template` option is not present. I was surprised to see the option missing because it is available in the `knife boostrap` command.

**Comment by jjasghar** [comment] 2015-05-07 18:28
Odd, yeah i'll take some time and find out how this missed this. Updates when i got em.

**Comment by jjasghar** [comment] 2015-06-04 23:43
Heh, so it seems we don't have that option. I thought it would be slurped up via [knife-cloud](https://github.com/chef/knife-cloud), but i guess i'm wrong.  I'm have a pre-release of [1.2.0](https://github.com/chef/knife-openstack/pull/165) baking for the time being. I'll slate some time for it next week, and if figure out how to add this, i'll push it with `1.2.0`.

```
        --bootstrap-curl-options OPTIONS
                                     Add options to curl when install chef-client
        --bootstrap-install-command COMMANDS
                                     Custom command to install chef-client
        --bootstrap-network NAME     Specify network for bootstrapping. Default is 'public'.
        --bootstrap-no-proxy [NO_PROXY_URL|NO_PROXY_IP]
                                     Do not proxy locations for the node being bootstrapped; this option is used internally by Opscode
        --bootstrap-protocol protocol
                                     Protocol to bootstrap servers. options: winrm/ssh. For linux servers always use ssh.
        --bootstrap-proxy PROXY_URL  The proxy server for the node being bootstrapped
        --bootstrap-url URL          URL to a custom installation script
        --bootstrap-version VERSION  The version of Chef to install
        --bootstrap-wget-options OPTIONS
                                     Add options to wget when installing chef-client
```

**Comment by jjasghar** [comment] 2015-06-05 19:44
@xrl so maybe i'm miss understanding, but it looks like `        --template-file TEMPLATE     Full path to location of template to use`  is the option you're looking for. If you look at: https://docs.chef.io/knife_bootstrap.html#custom-templates i think it's what you're looking for.

Please reopen this if it's still an issue.

**Comment by jjasghar** [comment] 2015-06-05 21:35
Ok, so it seems I was doubly wrong: https://github.com/chef/knife-cloud/pull/85/files#diff-3503536858f753f9066eca592720490eR113 shows that it's not in `knife-cloud` and _will_ be. I'll keep an eye on https://github.com/chef/knife-cloud/pull/85 and update knife-openstack when it's pushed.

**Comment by NimishaS** [comment] 2015-06-09 07:18
@jjasghar , https://github.com/chef/knife-cloud/pull/85 is merged

**Comment by jjasghar** [comment] 2015-06-09 20:00
@xrl confirmed that the changes above works with the newest version of knife-openstack. I'll bump the version for 1.1.1 knife-cloud.

**Closed by jjasghar** 2015-06-09 20:00 UTC

**Comment by jjasghar** [comment] 2015-06-10 20:13
This has been released/fixed via the new rc2 release. it'll be resolved in the main release too.

**Comment by xrl** [comment] 2015-07-17 19:58
Thanks, I had issues finding the right gem to run this on but now 1.2.0 is working just dandy. Thanks!
