### ISSUE TITLE
 uninitialized constant Chef::Knife::Cloud::Command (NameError)

### ISSUE THREAD

**Issue by b-slim** [chef/knife-openstack#172] opened 2015-07-22 21:52 UTC
Hello Guys,
we have updated recently our build machines to use ruby 2.2.2 (was 2.1.4) and now we get this error.
Any ideas why this is happening ?
```
00:03:05.374 /home/screwdrv/.rvm/gems/ruby-2.2.2/gems/knife-openstack-1.3.1/lib/chef/knife/openstack_floating_ip_release.rb:12:in `<class:Cloud>': uninitialized constant Chef::Knife::Cloud::Command (NameError)
00:03:05.374 	from /home/screwdrv/.rvm/gems/ruby-2.2.2/gems/knife-openstack-1.3.1/lib/chef/knife/openstack_floating_ip_release.rb:11:in `<class:Knife>'
00:03:05.375 	from /home/screwdrv/.rvm/gems/ruby-2.2.2/gems/knife-openstack-1.3.1/lib/chef/knife/openstack_floating_ip_release.rb:10:in `<class:Chef>'
00:03:05.375 	from /home/screwdrv/.rvm/gems/ruby-2.2.2/gems/knife-openstack-1.3.1/lib/chef/knife/openstack_floating_ip_release.rb:9:in `<top (required)>'
00:03:05.376 	from /home/screwdrv/.rvm/gems/ruby-2.2.2/gems/chef-12.4.1/lib/chef/knife/core/subcommand_loader.rb:44:in `load'
00:03:05.376 	from /home/screwdrv/.rvm/gems/ruby-2.2.2/gems/chef-12.4.1/lib/chef/knife/core/subcommand_loader.rb:44:in `block in load_commands'
00:03:05.377 	from /home/screwdrv/.rvm/gems/ruby-2.2.2/gems/chef-12.4.1/lib/chef/knife/core/subcommand_loader.rb:44:in `each'
00:03:05.377 	from /home/screwdrv/.rvm/gems/ruby-2.2.2/gems/chef-12.4.1/lib/chef/knife/core/subcommand_loader.rb:44:in `load_commands'
00:03:05.377 	from /home/screwdrv/.rvm/gems/ruby-2.2.2/gems/chef-12.4.1/lib/chef/knife.rb:128:in `load_commands'
00:03:05.378 	from /home/screwdrv/.rvm/gems/ruby-2.2.2/gems/chef-12.4.1/lib/chef/knife.rb:209:in `run'
00:03:05.378 	from /home/screwdrv/.rvm/gems/ruby-2.2.2/gems/chef-12.4.1/lib/chef/application/knife.rb:142:in `run'
00:03:05.379 	from /home/screwdrv/.rvm/gems/ruby-2.2.2/gems/chef-12.4.1/bin/knife:25:in `<top (required)>'
00:03:05.379 	from /home/screwdrv/.rvm/gems/ruby-2.2.2/bin/knife:23:in `load'
00:03:05.379 	from /home/screwdrv/.rvm/gems/ruby-2.2.2/bin/knife:23:in `<main>'
00:03:05.380 	from /home/screwdrv/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
00:03:05.401 	from /home/screwdrv/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
00:03:08.709 [2015-07-22T15:44:53+00:00] WARN: Force Deleting client and node objects from chef-server
```

**Comment by jjasghar** [comment] 2015-07-22 21:54
What command are you running? It looked like you tried to release a floating ip?

**Comment by b-slim** [comment] 2015-07-22 21:57
it is `bundle exec knife openstack server delete --yes --purge NODE_NAME`

**Comment by jjasghar** [comment] 2015-07-22 21:58
crap, ok, i'll take a look asap.

**Comment by jjasghar** [comment] 2015-07-22 22:11
what version of `knife-cloud` do you have installed?

**Comment by jjasghar** [comment] 2015-07-22 22:12
please make sure you're on the newest version of knife-cloud, i just repo'd it with the older version.

**Comment by b-slim** [comment] 2015-07-22 22:16
@jjasghar as you can see in the stack i am using the `1.3.1` thought it is the latest

**Comment by b-slim** [comment] 2015-07-22 22:19
here is the is the versions 
```
00:02:54.712 Installing knife-cloud 1.2.0
00:02:54.781 Installing fog 1.32.0
00:02:54.828 Installing knife-openstack 1.3.1
```

**Comment by jjasghar** [comment] 2015-07-22 22:23
Hmm, that is the newest version of knife-cloud. can you double check to see if you might have multiple versions installed?

**Comment by b-slim** [comment] 2015-07-22 22:25
Will double check but i doubt, we are using a fresh docker build container each time.

**Comment by jjasghar** [comment] 2015-07-22 22:46
Just to do some sanity checks:

```
17:43:01 knife-openstack > (master) ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
17:44:17 knife-openstack > (master) bundle exec knife openstack server delete --yes --purge test
Instance Name: test
Instance ID: ec421c9a-fc22-4ca1-bf1f-fee6871900ae

WARNING: Deleted node test
WARNING: Deleted client test
17:44:31 knife-openstack > (master)
```

I was running the same version of ruby, knife-cloud, knife-openstack and blew away the machine. I wasn't able to repo.

**Comment by jjasghar** [comment] 2015-07-23 15:58
Any luck? Apart from the older version of knife-cloud, i havent been able to repo.

**Comment by b-slim** [comment] 2015-07-23 20:24
Well i have tried it again and it is working, i am really not sure what was wrong, thanks @jjasghar

**Comment by Cluster444** [comment] 2015-09-04 12:04
I just ran into this issue as well. It's happening because of the load order when the subcommand loader runs. Some of the commands within knife-openstack have requires that load some file that loads chef/knife/cloud/command, but the openstack releast floating ip subcommand does not require that. So when it loads first, that class has not been loaded by ruby yet, thus the failing error.

This is completely dependent on the load order, it may work some times or not be reproducible if the load order ends up being different. For example if openstack server create is loaded first, that has a proper require for chef/knife/cloud/server/create_command which in turn requires chef/knife/cloud/command.

**Comment by b-slim** [comment] 2015-09-04 16:26
We are getting this issue again, more often, how one can ensure that the proper loading will take place ?

**Comment by jjasghar** [comment] 2015-09-04 16:29
It looks like i'll need to push out @Cluster444 's fix. I'm going to test it today and ideally release a pre-release today. And ask yall to test it.

**Comment by b-slim** [comment] 2015-09-04 16:31
@jjasghar Thanks !

**Comment by Vasu1105** [comment] 2015-09-04 17:20
@Cluster444  Thanks !

**Comment by b-slim** [comment] 2015-09-04 19:16
As a workaround i am already using @Cluster444 branch and it is working good so far, Thanks guys !

**Comment by jjasghar** [comment] 2015-09-04 19:34
Ah, cool, can you try the prerelease gem too? I have merged it in and already pushed it to rubygems.

**Comment by b-slim** [comment] 2015-09-04 19:42
@jjasghar unfortunately i can't, we rely on a yahoo mirror based gem and they don't expose dev gems i guess

**Comment by jjasghar** [comment] 2015-09-04 19:44
Ah, that's a problem. I'll give it a few days to bake and if you do se any issues please post them in #177 and we can track the release there. I'm going to close this per that issue now.

**Closed by jjasghar** 2015-09-04 19:44 UTC
